server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url: # Eureka服务地址(集群)
      defaultZone: http://127.0.0.1:10086/eureka #集群配置方式：defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    registry-fetch-interval-seconds: 5   # 拉取注册的信息
    instance-info-replication-interval-seconds: 5  # 实例信息替换的时间
    initial-instance-info-replication-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
logging:
  level:   # debug   info   warn   error
    root: info
    com.leyou: debug
ly:
  jwt:
    pubKeyPath: E:/rsa/id_rsa.pub # 公钥地址
    priKeyPath: E:/rsa/id_rsa # 私钥地址
  user:
    expire: 30 #过期时间设置
    cookieName: LY_TOKEN # cookie名称
    cookieDomain: leyou.com # cookie的域
