server:
  port: 8087
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.13.111:3303/leyou?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: passw0rd
mybatis:
  type-aliases-package: com.leyou.auth.entity
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
  mapper-locations: mapper/*.xml
mapper:
  wrap-keyword: "`{0}`"  #处理实体类属性名字是Mysql关键字的方法
eureka:
  client:
    service-url: # Eureka服务地址(集群)
      defaultZone: http://127.0.0.1:10086/eureka #集群配置方式：defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    registry-fetch-interval-seconds: 5   # 拉取注册的信息
    instance-info-replication-interval-seconds: 5  # 实例信息替换的时间
    initial-instance-info-replication-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
logging:
  level:   # debug   info   warn   error
    root: info
    com.leyou: debug
ly:
  jwt:
    pubKeyPath: E:/rsa/id_rsa.pub # 公钥地址
    priKeyPath: E:/rsa/id_rsa # 私钥地址
    user:
      expire: 30 #过期时间设置
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域
      refreshTime: 10 #刷新时间
    app:
      expire: 1500 #微服务过期时间设置
      id: 10 # auth服务的id
      name: auth-service # 服务名称
      headerName: privilege_toker
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 10 # 加密强度4~31，决定了密码和盐加密时的运算次数，超过10以后加密耗时会显著增加
